### PR TITLE
Coordinates_of_plantings_2019.csv: adding to data file

### PR DESCRIPTION
**Pull request by Danielcalza**
Add the planting coordinates to the data file.

### CODE REVIEW

**Comment by brymz** [comment]
Does this data file use best practices for data structure and organization?

**Comment by Danielcalza** [comment]
No, it did not. I found the errors and have updated the file, but for some reason, even though I pushed it, the updated commit is not showing up to override this one. Am I missing something?

**Comment by brymz** [comment]
Did you push to the `hemp-gps` branch?

**Comment by Danielcalza** [comment]
Yes I did.

**Comment by brymz** [comment]
Hm. Well, I see changes now.

Get rid of the `"`. Then we're good.

**Comment by Danielcalza** [comment]
Okay sounds good, although I'm not sure where the floating quotation is, I'm still looking thought the commit and the log on the command prompt.

**Comment by brymz** [comment]
Immediately before the latitude and immediately after the longitude. For example:

```
PilotPlot1,"25.5106648, -80.5035612",
```

**Comment by Danielcalza** [comment]
Okay, I see what happened, it was treating them as a character string so they should have been separated into different columns. I made the edits and then reviewed them. All looks good now.

**Pull request merged**
